AWSTemplateFormatVersion: "2010-09-09"
Description: "Despliegue de NextCloud con alta disponibilidad en AWS"

Resources:
  # VPC
  JDGVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-JDG-CF

  # Subredes públicas y privadas
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref JDGVPC
      CidrBlock: "10.0.0.0/24"
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-Subnet-1-CF

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref JDGVPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: Private-Subnet-1-CF

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref JDGVPC
      CidrBlock: "10.0.2.0/24"
      AvailabilityZone: "us-east-1b"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-Subnet-2-CF

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref JDGVPC
      CidrBlock: "10.0.3.0/24"
      AvailabilityZone: "us-east-1b"
      Tags:
        - Key: Name
          Value: Private-Subnet-2-CF

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: VPC-JDG-InternetGateway-CF

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref JDGVPC
      InternetGatewayId: !Ref InternetGateway

  # Tabla de rutas públicas
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref JDGVPC
      Tags:
        - Key: Name
          Value: MyPRT-CF

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  # Asociaciones de tabla de rutas
  AssociateRouteTable1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  AssociateRouteTable2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Elastic IP para NAT Gateway
  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  # NAT Gateway
  NatGateway:
    Type: AWS::EC2::NatGateway
    DependsOn:
      - AttachGateway
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  # Tabla de rutas privadas
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref JDGVPC
      Tags:
        - Key: Name
          Value: Private-Route-Table

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NatGateway

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

    # Application Load Balancer (ALB)
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: "NextCloudALB"
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref GSALB
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: ALB-NextCloud

  # ALB Listener
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "NextCloudTargetGroup"
      VpcId: !Ref JDGVPC
      Protocol: HTTP
      Port: 80
      TargetType: "instance"
      HealthCheckPath: "/"
      Tags:
        - Key: Name
          Value: TargetGroup-NextCloud

    # Creación del EFS
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      PerformanceMode: "generalPurpose"
      ThroughputMode: "bursting"
      FileSystemTags:
        - Key: Name
          Value: "NextCloudEFS"
      BackupPolicy:
        Status: "ENABLED"

  # Puntos de montaje en subredes privadas
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref PrivateSubnet1
      SecurityGroups:
        - !Ref GSEFS

  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref PrivateSubnet2
      SecurityGroups:
        - !Ref GSEFS

  # LaunchTemplate, Grupo de Auto Scaling y Balanceador de Carga

  # LaunchTemplate:
  #   Type: AWS::EC2::LaunchTemplate
  #   Properties:
  #     LaunchTemplateData:
  #       ImageId: "ami-04b4f1a9cf54c11d0"
  #       InstanceType: "t3.micro"
  #       KeyName: "nextcloudkey"
  #       SecurityGroupIds:
  #         - !Ref GSWEB
  #       IamInstanceProfile:
  #         Name: "LabInstanceProfile"
  #     LaunchTemplateName: "NextCloudLaunchTemplate"

  # AutoScalingGroup:
  #   Type: AWS::AutoScaling::AutoScalingGroup
  #   Properties:
  #     VPCZoneIdentifier:
  #       - !Ref PrivateSubnet1
  #       - !Ref PrivateSubnet2
  #     LaunchTemplate:
  #       LaunchTemplateId: !Ref LaunchTemplate
  #       Version: "1"
  #     MinSize: 2
  #     MaxSize: 6
  #     DesiredCapacity: 2
  #     TargetGroupARNs:
  #       - !Ref TargetGroup
  EC2InstancePublic:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-04b4f1a9cf54c11d0" # Ubuntu 24.04 (verifica ID en tu región)
      InstanceType: "t3.micro"
      KeyName: "nextcloudkey" # Asegúrate de que la clave existe
      SecurityGroupIds:
        - !Ref GSWEB
      SubnetId: !Ref PublicSubnet1
      IamInstanceProfile: "LabInstanceProfile"
      Tags:
        - Key: Name
          Value: "EC2-Public-NextCloud"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdh" # Puedes elegir otro nombre, /dev/sdh es solo un ejemplo
          Ebs:
            VolumeSize: 8
            VolumeType: "gp3"
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # set -eux  # Activa errores y modo depuración

          # Actualiza paquetes e instala utilidades
          apt update -y
          apt install -y amazon-efs-utils nfs-common apache2

          # Activa Apache
          systemctl enable apache2
          systemctl start apache2

          usermod -a -G www-data ubuntu
          chown -R ubuntu:www-data /var/www/
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          apt install php libapache2-mod-php php-mysql php-gd php-curl php-xml -y
          apt install php-mbstring php-intl php-gmp php-bcmath php-imagick php-zip unzip -y
          apt install nfs-common -y

          # Monta el EFS
          # mkdir -p /mnt/efs
          # mount -t efs ${FileSystem}:/ /mnt/efs

          # Agrega el montaje a fstab para que persista tras reinicios
          # echo "${FileSystem}:/ /mnt/efs efs defaults,_netdev 0 0" >> /etc/fstab

  # Base de Datos RDS (MariaDB)
  RDSDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: mariadb
      EngineVersion: "10.5"
      MasterUsername: admin
      MasterUserPassword: "adminadmin"
      DBName: nextcloud
      AllocatedStorage: 20
      StorageType: gp2
      MultiAZ: true
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !Ref GSBBDD
      PubliclyAccessible: false
      BackupRetentionPeriod: 0
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: NextCloud-DB

  # DB Subnet Group
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subredes de la base de datos RDS"
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: "RDS-DB-Subnet-Group"

  # Grupos de Seguridad
  GSALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permite trfico HTTP entrante desde cualquier sitio"
      VpcId: !Ref JDGVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Permite trfico IPv4 desde cualquier origen

  GSWEB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permite trfico entrante HTTP slo desde GS-ALB"
      VpcId: !Ref JDGVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          SourceSecurityGroupId: !Ref GSALB
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"

  GSBBDD:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permite trfico entrante al puerto de MySQL/MariaDB (3306) desde GS-WEB"
      VpcId: !Ref JDGVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "3306"
          ToPort: "3306"
          SourceSecurityGroupId: !Ref GSWEB

  GSEFS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permite trfico entrante al puerto NFS desde GS-WEB"
      VpcId: !Ref JDGVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "2049"
          ToPort: "2049"
          SourceSecurityGroupId: !Ref GSWEB
