AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para la tarea 4_2_1"
Parameters:
  Mappings:
    # AvailabilityZone:
    #   us-east-1:
    #     Name: us-east-1a
    #   us-west-1:
    #     Name: us-west-1a
    #   us-west-2:
    #     Name: us-west-2a
    AvailabilityZone:
      us-east-1:
        AZ1: us-east-1a
        AZ2: us-east-1b
        AZ3: us-east-1c
      us-east-2:
        AZ1: us-east-2a
        AZ2: us-east-2b
        AZ3: us-east-2c
      us-west-1:
        AZ1: us-west-1a
        AZ2: us-west-1b
        AZ3: us-west-1c
      us-west-2:
        AZ1: us-west-2a
        AZ2: us-west-2b
        AZ3: us-west-2c
        
  CreateIGW:
    Description: "Create Internet Gateway"
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

Conditions:
  CreateIGW: !Equals [!Ref CreateIGW, "true", "false"]
Resources:
  VPC422:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/20"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-4-2-2