AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para la tarea 4_2_1"
Parameters:
  CreateIGW:
    Description: "Create Internet Gateway"
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    ConstraintDescription: "Must be true or false"

Conditions:
  # CreateIGW:
  #   Description: "Create Internet Gateway"
  #   Type: String
  #   Default: "true"
  #   AllowedValues: ["true", "false"]
  #   ConstraintDescription: "Must be true or false"

  YesCreateIGW: !Equals [!Ref CreateIGW, "true"]

  CreateIGWAffirmative:
    !If [YesCreateIGW, true, false]
    # !Equals [!Ref CreateIGW, "true"]

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Condition: CreateIGWAffirmative
    Properties:
      Tags:
        - Key: Name
          Value: IGW-4-2-2-Afirmative-Redundant
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: CreateIGWAffirmative
    Properties:
      # VpcId: !Ref VPC422A
      InternetGatewayId: !Ref InternetGateway
