AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para la tarea 4_2_1"
Parameters:
  CreateIGW:
    Description: "Create Internet Gateway"
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    ConstraintDescription: "Must be true or false"

Conditions:
  # CreateIGW:
  #   Description: "Create Internet Gateway"
  #   Type: String
  #   Default: "true"
  #   AllowedValues: ["true", "false"]
  #   ConstraintDescription: "Must be true or false"

  YesCreateIGW: !Equals [!Ref CreateIGW, "true"]

  # CreateIGWAffirmative:
  #   !If [YesCreateIGW, "true", "false"]
  #   # !Equals [!Ref CreateIGW, "true"]

Resources:
  VPC421:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-4-2-2

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Condition: YesCreateIGW
    Properties:
      VpcId: !Ref VPC421
      Tags:
        - Key: Name
          Value: IGW-4-2-2-Afirmative-Redundant
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: YesCreateIGW
    Properties:
      VpcId: !Ref VPC421
      InternetGatewayId: !Ref InternetGateway
