AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para la tarea 4_2"
Parameters:
  # EnvironmentType:
  #   Description: "Specify the Environment type of the stack."
  #   Type: String
  #   Default: dev
  #   AllowedValues:
  #     - dev
  #     - test
  #     - prod
  CreateEC2:
    Description: "Create EC2 instance"
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  InstanceType:
    Description: "Instance type"
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - "t2.micro"
      - "t2.small"
      - "t2.medium"
# Mappings:
#   EnvironmentToInstanceType:
#     dev:
#       InstanceType: t2.micro
#     test:
#       InstanceType: t2.small
#     prod:
#       InstanceType: t2.medium
Rules:
  TypeEc2:
    Assertions:
      - Assert:
          "Fn::Contains":
            - ["t2.micro", "t2.small", "t2.medium"]
            - !Ref InstanceType
    Assert: "true"

Conditions:
  CreateEC2: !Equals [!Ref CreateEC2, "true"]

Resources:
  # VPC
  VPC421:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-4-2-1
  # Subred públicas
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC421
      CidrBlock: "10.0.0.0/24"
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-Subnet-4-2-1

  # EC2 Instance
  WebAppInstance:
    Type: AWS::EC2::Instance
    Condition: CreateEC2
    Properties:
      AvailabilityZone: "us-east-1a"
      ImageId: "ami-04b4f1a9cf54c11d0"
      InstanceType:
        Ref: InstanceType
      KeyName: vockey
  
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Join ["-", [!GetAtt PublicSubnet1.AvailabilityZone, "Pedro"]] 
        - Key: VPCID
          Value: !GetAtt VPC421.VpcId

# Outputs:
#   WebAppInstanceID:
#     Value: !Ref WebAppInstance
#     Description: "ID de la instancia EC2"
#   WebAppSecurityGroupID:
#     Value: !GetAtt WebAppSecurityGroup.GroupId
#     Description: "ID del grupo de seguridad"
#   WebAppPublicIP:
#     Value: !GetAtt WebAppInstance.PublicIp
#     Description: "IP pública de la instancia EC2"
