AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para la tarea de redes Route 53"
Resources:
  #VPC
  VPC421:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-4-2-1
  #Instancia EC2 Ubuntu server
  EC2UbuntuServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-053a45fff0a704a47"
      InstanceType: "t2.micro"
      KeyName: "vockey"
      SecurityGroups:
        - !Ref WebAppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf install -y httpd 
          systemctl start httpd.service
          systemctl enable httpd.service
          echo "<h1>Welcome to Apache Web Server</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: "EC2-Ubuntu-Server"
  #Instancia EC2 Windows server
  EC2WindowsServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-07fa5275316057f54"
      InstanceType: "t3.micro"
      KeyName: "vockey"
      SecurityGroups:
        - !Ref WebAppSecurityGroup
      Tags:
        - Key: Name
          Value: "EC2-Windows-Server"

  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "SecurityGroup-WebApp"
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

  DNS:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: 'Hosted zone for WebApp'
      Name: 'as.com'
      VPCs:
        - VPCId: !Ref VPC421
          VPCRegion: !Ref AWS::Region
      PrivateZone: true


  myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref DNS
      Name: www.as.com
      ResourceRecords:
      - !GetAtt EC2UbuntuServer.PrivateIp
      TTL: 900
      Type: A


